### ISSUE TITLE
Sent image only filled with zeros

### ISSUE THREAD

**Issue by j-lnaddef** [giuse/vtorcs#2]
I am using your code through gym torcs https://github.com/ugo-nama-kun/gym_torcs, and I realized the images I receive are only filled with 0.
At first I thought it was due to my gym-torcs configuration, but then it appeared it is the image received from your code that is like that.

If I understand correctly, the image to send is created in /src/libs/raceengineclient/raceengine.cpp -> VisionUpdate(). I put a printf there and all pixels are set to 0.

Do you know what might be happening?

**Comment by giuse** [comment]
Make sure the server can render the image on the screen, and that the window is not covered by another. The way it works is by grabbing the pixels rendered for an area of the screen, so you can get zeros (or other crazy values) if something gets on top.
If not so, I would contact the author of gym_torcs. Good luck!

**Comment by j-lnaddef** [comment]
Well the game is indeed rendered on my screen, with nothing covering it.

I am running gym_torcs in a VM, as it supports only Ubuntu, do you think this could interfere with your code grabbing the pixels from the screen?

**Comment by giuse** [comment]
That might likely be it, depending on the settings of your VM, since it means you are actually virtualizing what the ubuntu machine should be showing on screen. If you want to check, I suggest you download a bootable ubuntu image, launch ubuntu without installing, open your code and see if it works there. If so you might want to dedicate a small partition to install ubuntu, it's a straightforward process nowadays.
